-- Seed data — these photos persist forever (is_seed = true)
INSERT INTO photos (image_path, caption, is_seed, user_id, author_name) VALUES
  ('seed-01.jpg', 'When the code finally compiles', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-02.jpg', 'Office dog says hi', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-03.jpg', 'Abstract art by a robot', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-04.jpg', 'Sunset generated by AI', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-05.jpg', '404: Sleep not found', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-06.jpg', 'The cloud is just someone else''s computer', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-07.jpg', 'Debugging mood', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-08.jpg', 'When you fix one bug and create three more', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-09.jpg', 'Monday morning vibes', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-10.jpg', 'The rubber duck knows all', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-11.jpg', 'Deploy on Friday? Sure, what could go wrong', true, '00000000-0000-0000-0000-000000000000', 'bld402'),
  ('seed-12.jpg', 'Stack overflow to the rescue', true, '00000000-0000-0000-0000-000000000000', 'bld402');
